version: "3"
services:

    app:
        build:
            dockerfile: Dockerfile
            context: ./docker/app
            args:
                APP_ENV: 'prod'
                COMPOSER_NO_DEV: '1'
                PHP_OPCACHE_ENABLE: '1'
                PHP_XDEBUG_MODE: ''
                PHP_XDEBUG_CLIENT_PORT: '9003'
                PHP_XDEBUG_CLIENT_HOST: 'host.docker.internal'
                AUTOSTART_APP_DAEMONS: 'true'
                UID: '82'
                GID: '82'
        volumes:
            - "./app:/var/www/app"
            - "./db:/var/www/app/var/db"

    server:
        build:
            dockerfile: Dockerfile
            context: ./docker/nginx
            args:
                UID: '1000'
                GID: '1000'
                CERTBOT_RENEW: 'yes'
        volumes:
            - ./app:/var/www/app
            - ./docker/nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
            - ./docker/nginx/templates/letsencrypt-challenge.conf.template:/etc/nginx/templates/letsencrypt-challenge.conf.template
            - ./docker/nginx/templates/ssl.conf.template:/etc/nginx/templates/ssl.conf.template
            - ./docker/nginx/letsencrypt:/etc/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        env_file:
            - .env
            - .env.nginx.prod

volumes:
    db-data:

