version: "3"
services:

    app:
        build:
            dockerfile: Dockerfile
            context: ./docker/app
            args:
                APP_ENV: 'dev'
                COMPOSER_NO_DEV: '0'
                PHP_OPCACHE_ENABLE: '0'
                PHP_XDEBUG_MODE: 'debug'
                PHP_XDEBUG_CLIENT_PORT: '9003'
                PHP_XDEBUG_CLIENT_HOST: '172.17.0.1'
                AUTOSTART_APP_DAEMONS: 'false'
                UID: '1000'
                GID: '1000'
        environment:
            PHP_IDE_CONFIG: "serverName=app"
        volumes:
            - "./app:/var/www/app"
            - "./db:/var/www/app/var/db"
        ports:
            - "9001:9001"

    server:
        build:
            dockerfile: Dockerfile
            context: ./docker/nginx
            args:
                UID: '1000'
                GID: '1000'
                CERTBOT_RENEW: 'no'
        volumes:
            - ./app:/var/www/app
            - ./docker/nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
        ports:
            - "80:80"
        env_file:
            - .env
            - .env.nginx.dev

volumes:
    db-data:
